language: python
python:
    - "3.6"
    - "3.7"
    - "3.8"

install:
    - pip install pylint

script:
    - "./build.sh"
    - pylint $(find src/ -name '*.py')

before_deploy:
    - "./build.sh --deploy"

deploy:
    provider: releases
    api_key:
        secure: HdbTytnpgf4V8zkIju4GxFhC8Wi4F7pieREBOPxHL7jHmiyddCk6Usjg6m2HQTW4fD1V0XxZ2dx2qEP9FBC9a+DIRXVyWAzzntjx/2REBl/XxLSG6Q3Tyyavn+sfA8jFoJ5klokso6NAixiZ5VU9BMcpMQznMT2qx/9bLt8Vgp0vnJH7M7zoVR35wD05mNwgJUQQa+vwisCQ4tNTpNqGHbyPRrS6St54SrITwph4Rs5Pb0IFMbgAz04kcp++zn/4e6JTrebGN+3fHZy8xL2gaKsY8adMH/thKOmOd6dJPjCVCcD1QQsoaxtueCb7Z7fCLZ+HNSB4Bf94eqaQLB2I4LO9yM1t+mIrMidG8hdhOveQic3Zx+qB4TeQLqFIqREjVcPu6TIiAR0KedNGnvDvFuytJSeO8gIOVfM8yqdjX7lVy/50h3tSdnAhjBHkXzP1icG5zwLUZjIeEL/cEf3aeITS8g1VaeU1jE6+qkR7i/ngDmLsc4VjS3gVIPIp7+4Y4uHicWGPxj5nUfthPBHpQY72TNRygMwQIetQSONsTOHf/uHxOfALyqGHbg0iTwp7o2rsK/tyc9eWsQtTZI8ZaZLY8zVRA/3iGYDFMMbcC2HDO3Aoc8rkk3Hz2Rkzz/VM5Nx+iEfB1AOZWW8Ai6EHL7wp/0ma63S0dF7daqhBFvQ=
    file: "dist/ControlAnySim.zip"
    skip_cleanup: true
    draft: true
    on:
        tags: true
        repo: TitanNano/TS4ControlAnySim
